# File: FE/app.py
import streamlit as st
import os
import subprocess
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "outputs" / "sample_repo"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

st.title("Codebase Genius Frontend 🚀")
st.write("Interact with Jac backend and generate documentation and diagrams.")

# --- User Input ---
repo_path = st.text_input("Enter path to your repository (local folder):", "")
generate_docs = st.checkbox("Generate Documentation (docs.md)")
generate_diagram = st.checkbox("Generate Diagram (ccg.svg)")

# --- Buttons ---
if st.button("Run Jac Backend"):
    if not repo_path:
        st.warning("Please enter a repository path.")
    else:
        st.info("Running Jac backend...")
        try:
            # Call Jac scripts using subprocess
            subprocess.run(
                ["jac", "serve", str(BASE_DIR / "BE" / "jac" / "main.jac")],
                cwd=str(BASE_DIR / "BE"),
                check=True
            )
            st.success("Jac backend started successfully!")
        except subprocess.CalledProcessError as e:
            st.error(f"Error running Jac backend:\n{e}")

if st.button("Generate Outputs"):
    st.info("Generating outputs...")

    # Generate docs.md
    if generate_docs:
        doc_path = OUTPUT_DIR / "docs.md"
        doc_path.write_text("# Sample Documentation\nGenerated by Codebase Genius.\n")
        st.success(f"Documentation saved: {doc_path}")

    # Generate diagram ccg.svg
    if generate_diagram:
        diagram_path = OUTPUT_DIR / "ccg.svg"
        diagram_path.write_text(
            """<svg height="100" width="200">
  <rect width="200" height="100" style="fill:blue;stroke-width:3;stroke:rgb(0,0,0)" />
  Sorry, your browser does not support inline SVG.  
</svg>"""
        )
        st.success(f"Diagram saved: {diagram_path}")

st.write("Outputs will be saved in:", OUTPUT_DIR)
